import "../globals.css";

export const metadata = {
  title: "Watch Later - CimaZone",
  description: "Generated by create next app",
};

export default function WatchLaterLayout({ children }) {
  return (
      <>
        {children}
      </>
  );
}
