import "../globals.css";

export const metadata = {
  title: "Favorites - CimaZone",
  description: "Generated by create next app",
};

export default function FavoritesLayout({ children }) {
  return (
      <>
        {children}
      </>
  );
}
